build:
  cuda_version: "12.1.1"
  python_packages:
    - "torch==2.6.0"
    - "vllm==0.8.1"
    - "bitsandbytes==0.45.3"
    - "hf-transfer==0.1.9"
    - "huggingface-hub==0.29.3"
    - "git+https://github.com/huggingface/transformers.git"
    - "accelerate==1.5.2"
